/*
 * Copyright (c) 2020 Raspberry Pi (Trading) Ltd.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

// ---------------------------------------
// THIS FILE IS AUTOGENERATED; DO NOT EDIT
// ---------------------------------------

#ifndef _PICO_CONFIG_AUTOGEN_H
#define _PICO_CONFIG_AUTOGEN_H

// Basic configuration for RT-Thread integration
#define PICO_DEFAULT_UART 0
#define PICO_DEFAULT_UART_TX_PIN 0
#define PICO_DEFAULT_UART_RX_PIN 1

// Disable some features that might conflict with RT-Thread
#define PICO_NO_HARDWARE 0
#define PICO_ON_DEVICE 1

// Platform specific configuration
#ifdef PICO_TARGET_PLATFORM
#if PICO_TARGET_PLATFORM == rp2350
#define PICO_CYW43_ARCH_POLL 0
#define PICO_CYW43_ARCH_THREADSAFE_BACKGROUND 0
#endif
#endif

#endif
