import rtconfig
Import('RTT_ROOT')
from building import *
import os

# get current directory
cwd = GetCurrentDir()
src = []
path = []

# 从环境变量获取平台配置
TARGET_PLATFORM = os.environ.get('TARGET_PLATFORM', 'rp2350')
PLATFORM_SRC_DIR = os.environ.get('PLATFORM_SRC_DIR', 'rp2350')

# Add CMSIS source files and header files' path
if TARGET_PLATFORM == 'rp2040':
    src += Split("""
    rp2_common/cmsis/stub/CMSIS/Device/RaspberryPi/RP2040/Source/system_RP2040.c
    """)
    
    path += [
        cwd + '/rp2_common/cmsis/stub/CMSIS/Core/Include',
        cwd + '/rp2_common/cmsis/stub/CMSIS/Device/RaspberryPi/RP2040/Include',
        ]
elif TARGET_PLATFORM == 'rp2350':
    # RP2350 可能使用不同的CMSIS文件，暂时跳过
    pass

# The set of source files associated with this SConscript file.
src += Split("""
rp2_common/hardware_flash/flash.c
rp2_common/pico_multicore/multicore.c
rp2_common/pico_stdlib/stdlib.c
rp2_common/hardware_gpio/gpio.c
rp2_common/hardware_adc/adc.c
rp2_common/hardware_watchdog/watchdog.c
common/hardware_claim/claim.c
rp2_common/hardware_sync/sync.c
rp2_common/hardware_sync_spin_lock/sync_spin_lock.c
rp2_common/hardware_uart/uart.c
rp2_common/hardware_spi/spi.c
rp2_common/hardware_dma/dma.c
rp2_common/hardware_i2c/i2c.c
common/pico_time/time.c
common/pico_time/timeout_helper.c
rp2_common/hardware_timer/timer.c
common/pico_sync/sem.c
common/pico_sync/lock_core.c
common/pico_sync/mutex.c
common/pico_sync/critical_section.c
common/pico_util/datetime.c
common/pico_util/pheap.c
common/pico_util/queue.c
rp2_common/pico_runtime/runtime.c
rp2_common/hardware_clocks/clocks.c
rp2_common/hardware_xosc/xosc.c
rp2_common/hardware_pll/pll.c
rp2_common/hardware_vreg/vreg.c
rp2_common/hardware_irq/irq.c
rp2_common/pico_printf/printf.c
rp2_common/pico_bootrom/bootrom.c
rp2_common/pico_double/double_math.c
rp2_common/pico_float/float_init_rom.c
rp2_common/pico_malloc/pico_malloc.c
rp2_common/pico_standard_link/binary_info.c
rp2_common/pico_stdio/stdio.c
rp2_common/pico_stdio_uart/stdio_uart.c
rp2_common/pico_standard_link/new_delete.cpp
rp2_common/hardware_irq/irq_handler_chain.S
rp2_common/pico_double/double_conv_m33.S
rp2_common/pico_int64_ops/pico_int64_ops_aeabi.S
rp2_common/pico_float/float_v1_rom_shim.S
rp2_common/pico_mem_ops/mem_ops_aeabi.S
rp2_common/pico_standard_link/crt0.S

""")

# 平台特定的启动文件
if TARGET_PLATFORM == 'rp2040':
    src += ['../bs2_default_padded_checksummed.S']
elif TARGET_PLATFORM == 'rp2350':
    # RP2350 可能不需要 boot stage 2 文件
    pass

# 平台特定的源文件
if TARGET_PLATFORM == 'rp2040':
    src += ['rp2040/pico_platform/platform.c']
    src += ['rp2_common/hardware_divider/divider.S']  # RP2040 有 SIO 除法器硬件
    src += ['rp2_common/hardware_rtc/rtc.c']  # RP2040 有 RTC 硬件
    # RP2040 特定的 include 路径
    path += [
        cwd + '/rp2_common/hardware_rtc/include',
        cwd + '/rp2_common/hardware_divider/include',
    ]
elif TARGET_PLATFORM == 'rp2350':
    # 暂时跳过RP2350的platform.c，因为它有编译问题
    # src += ['rp2350/pico_platform/platform.c']
    pass

path += [
    cwd + '/rp2_common/hardware_flash/include',
    cwd + '/rp2_common/pico_flash/include',
    cwd + '/rp2_common/pico_multicore/include',
    cwd + '/common/pico_stdlib/include',
    cwd + '/rp2_common/hardware_gpio/include',
    cwd + '/rp2_common/hardware_adc/include',
    cwd + '/rp2_common/hardware_watchdog/include',
    cwd + '/common/pico_base/include',
    cwd + '/boards/include',
    cwd + '/rp2_common/pico_platform/include',
    cwd + f'/{PLATFORM_SRC_DIR}/hardware_regs/include',
    cwd + '/rp2_common/hardware_base/include',
    cwd + '/rp2_common/hardware_boot_lock/include',
    cwd + f'/{PLATFORM_SRC_DIR}/hardware_structs/include',
    cwd + '/common/hardware_claim/include',
    cwd + '/rp2_common/hardware_sync/include',
    cwd + '/rp2_common/hardware_sync_spin_lock/include',
    cwd + '/rp2_common/hardware_uart/include',
    cwd + '/rp2_common/hardware_dma/include',
    cwd + '/rp2_common/hardware_spi/include',
    cwd + '/rp2_common/hardware_i2c/include',
    cwd + '/rp2_common/hardware_pwm/include',
    cwd + '/rp2_common/hardware_rcp/include',  # RP2350 需要 RCP 硬件
    cwd + '/common/pico_time/include',
    cwd + '/rp2_common/pico_time_adapter/include',
    cwd + '/rp2_common/hardware_timer/include',
    cwd + '/common/pico_sync/include',
    cwd + '/common/pico_util/include',
    cwd + '/rp2_common/pico_runtime/include',
    cwd + '/rp2_common/pico_runtime_init/include',
    cwd + '/rp2_common/hardware_clocks/include',
    cwd + '/rp2_common/hardware_resets/include',
    cwd + '/rp2_common/hardware_watchdog/include',
    cwd + '/rp2_common/hardware_ticks/include',
    cwd + '/rp2_common/hardware_xosc/include',
    cwd + '/rp2_common/hardware_xip_cache/include',
    cwd + '/rp2_common/hardware_pll/include',
    cwd + '/rp2_common/hardware_vreg/include',
    cwd + '/rp2_common/hardware_irq/include',
    cwd + '/rp2_common/pico_printf/include',
    cwd + '/rp2_common/pico_bootrom/include',
    cwd + '/rp2_common/boot_bootrom_headers/include',
    cwd + '/common/boot_picoboot_headers/include',
    cwd + '/common/boot_picobin_headers/include',
    cwd + '/common/pico_bit_ops/include',
    cwd + '/common/pico_divider/include',
    cwd + '/rp2_common/pico_double/include',
    cwd + '/rp2_common/pico_int64_ops/include',
    cwd + '/rp2_common/pico_float/include',
    cwd + '/common/pico_binary_info/include',
    cwd + '/rp2_common/pico_stdio/include',
    cwd + '/rp2_common/pico_stdio_uart/include',
    cwd + '/rp2_common/pico_malloc/include',
    cwd + '/rp2_common/boot_stage2/include',
    ]

if GetDepend(['PKG_USING_WLAN_CYW43439']):
    path += [
        cwd + '/rp2_common/pico_unique_id/include',
        cwd + '/rp2_common/pico_async_context/include',
        cwd + '/rp2_common/pico_cyw43_driver/include',
        cwd + '/rp2_common/pico_lwip/include',
        cwd + '/rp2_common/pico_lwip/include/arch',
        cwd + '/rp2_common/pico_lwip/include/pico',
        cwd + '/rp2_common/hardware_pio/include',
        cwd + '/rp2_common/pico_rand/include',
    ]
    src += [
        cwd + '/rp2_common/pico_unique_id/unique_id.c',
        cwd + '/rp2_common/pico_cyw43_driver/cyw43_driver.c',
        cwd + '/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c',
        cwd + '/rp2_common/hardware_pio/pio.c',
        cwd + '/rp2_common/pico_async_context/async_context_base.c',
    ]

CPPDEFINES = [
    'PICO_NO_BINARY_INFO',
    'PICO_NO_PROGRAM_INFO',
    'PICO_BIT_OPS_PICO=1',
    'PICO_BUILD=1',
    # 'PICO_CMAKE_BUILD_TYPE=\\"Release\\"',
    'PICO_COPY_TO_RAM=0',
    'PICO_CXX_ENABLE_EXCEPTIONS=1',
    'PICO_DIVIDER_HARDWARE=1',
    'PICO_DOUBLE_PICO=1',
    'PICO_FLOAT_PICO=1',
    'PICO_INT64_OPS_PICO=1',
    'PICO_MEM_OPS_PICO=1',
    'PICO_NO_FLASH=0',
    'PICO_NO_HARDWARE=0',
    'PICO_ON_DEVICE=1',
    'PICO_PRINTF_PICO=1',
    'PICO_STDIO_UART=1',
    'PICO_USE_BLOCKED_RAM=0'
]
group = DefineGroup('raspberrypi-pico-sdk', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)


Return('group')
